#!/bin/bash

echo -n "Enter your PR number > "
read prNumber

branch_name="$(git symbolic-ref HEAD 2>/dev/null)" ||
branch_name="(unnamed branch)"
branch_name=${branch_name##refs/heads/}

heroku git:remote -a kissa-rc-project-pr-8
git push heroku $branch_name:master

echo Made for kissa!
